<%
out.println("<!DOCTYPE html>");
out.println("<html>");
out.println("   <head>");
out.println("      <!-- basic -->");
out.println("      <meta charset=\"utf-8\">");
out.println("      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
out.println("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
out.println("      <!-- mobile metas -->");
out.println("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
out.println("      <meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1\">");
out.println("      <!-- site metas -->");
out.println("      <title>CO</title>");
out.println("      <meta name=\"keywords\" content=\"\">");
out.println("      <meta name=\"description\" content=\"\">");
out.println("      <meta name=\"author\" content=\"\">");
out.println("      <!-- bootstrap css -->");
out.println("      <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">");
out.println("      <!-- style css -->");
out.println("      <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">");
out.println("      <!-- Responsive-->");
out.println("      <link rel=\"stylesheet\" href=\"css/responsive.css\">");
out.println("      <!-- fevicon -->");
out.println("      <link rel=\"icon\" href=\"images/fevicon.png\" type=\"image/gif\" />");
out.println("      <!-- font css -->");
out.println("      <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;800&display=swap\" rel=\"stylesheet\">");
out.println("      <!-- Scrollbar Custom CSS -->");
out.println("      <link rel=\"stylesheet\" href=\"css/jquery.mCustomScrollbar.min.css\">");
out.println("      <!-- Tweaks for older IEs-->");
out.println("      <link rel=\"stylesheet\" href=\"https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css\">");
out.println("   </head>");
out.println("   <body>");
out.println("      <div class=\"header_section header_bg\">");
out.println("         <div class=\"container-fluid\">");
out.println("            <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">");
out.println("               <a class=\"navbar-brand\"href=\"main.jsp\"><img src=\"images/logo.png\"></a>");
out.println("               <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">");
out.println("               <span class=\"navbar-toggler-icon\"></span>");
out.println("               </button>");
out.println("               <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">");
out.println("                  <ul class=\"navbar-nav ml-auto\">");
out.println("                     <li class=\"nav-item\">");
out.println("                        <a class=\"nav-link\" href=\"main.jsp\">Home</a>");
out.println("                     </li>");
out.println("                     <li class=\"nav-item\">");
out.println("                        <a class=\"nav-link\" href=\"Map.jsp\">Map</a>");
out.println("                     </li>");
out.println("                     <li class=\"nav-item\">");
out.println("                        <a class=\"nav-link\" href=\"Report.jsp\">Report</a>");
out.println("                     </li>");
out.println("                  </ul>");
out.println("                  <form class=\"form-inline my-2 my-lg-0\">");
out.println("                     <div class=\"login_bt\">");
out.println("                        <ul>");
out.println("                           ");
out.println("                           <li><a href=\"#\"><i class=\"fa fa-search\" aria-hidden=\"true\"></i></a></li>");
out.println("                        </ul>");
out.println("                     </div>");
out.println("                  </form>");
out.println("               </div>");
out.println("            </nav>");
out.println("         </div>");
out.println("      </div>");
out.println("      <!-- header section end -->");
out.println("      <!-- blog section start -->");
out.println("      <div class=\"blog_section layout_padding\">");
out.println("         <div class=\"container\">");
out.println("            <div class=\"row\">");
out.println("               <div class=\"col-md-12\">");
out.println("                  <h1 class=\"about_taital\">CO</h1>");
out.println("                  <div class=\"bulit_icon\"><img src=\"images/bulit-icon.png\"></div>");
out.println("               </div>");
out.println("            </div>");
out.println("            <div class=\"blog_section_2\">");
out.println("               <div class=\"row\">");
out.println("                  <div class=\"col-md-6\">");
out.println("                     <div class=\"blog_box\">");
out.println("                        <div class=\"blog_img\"><img src=\"images\\pm2.5.webp\"></div>");
out.println("                        <h4 class=\"date_text\">#5</h4>");
out.println("                        <h4 class=\"prep_text\">CO</h4>");
out.println("                        <p class=\"lorem_text\">CO, or carbon monoxide, is a colorless, odorless gas that can be harmful when inhaled, as it interferes with oxygen transport in the body.</p>");
out.println("                     </div>");
out.println("                  </div>");
out.println("                  <div class=\"col-md-6\">");
out.println("                     <div class=\"blog_box\">");
out.println("                        <div class=\"blog_img\"></div>");
out.println("                        <h4 class=\"prep_text\">Carbon monoxide (CO)...</h4>");
out.println("                        <p class=\"lorem_text\">");
out.println("Carbon monoxide (CO) is a colorless, odorless gas that can have harmful effects on human health. It is produced as a byproduct of incomplete combustion of carbon-containing fuels, such as wood, gasoline, and natural gas. When CO is inhaled, it binds to hemoglobin in the blood, reducing the blood's ability to carry oxygen to vital organs and tissues. This can lead to symptoms ranging from mild headaches and dizziness to more severe effects, including unconsciousness and death in cases of high exposure. CO poisoning is a serious concern, particularly in enclosed spaces with faulty heating systems, gas appliances, or inadequate ventilation. To prevent CO poisoning, it is crucial to install carbon monoxide detectors in homes and ensure proper maintenance of fuel-burning equipment, as well as adequate ventilation in enclosed spaces. Early detection and intervention are essential to prevent CO-related health problems.</p>");
out.println("                     </div>");
out.println("                  </div>");
out.println("               </div>");
out.println("            </div>");
out.println("         </div>");
out.println("      </div>");
out.println("<!-- about section end -->");
out.println("      <!-- client section start -->");
out.println("      <div class=\"client_section layout_padding\">");
out.println("         <div class=\"container\">");
out.println("            <div class=\"row\">");
out.println("               <div class=\"col-md-12\">");
out.println("                  <h1 class=\"about_taital\">Harm Full Effects</h1>");
out.println("                  <div class=\"bulit_icon\"><img src=\"images/bulit-icon.png\"></div>");
out.println("               </div>");
out.println("            </div>");
out.println("            <div class=\"client_section_2\">");
out.println("               <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images\\one.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Impaired Oxygen Transport</h3>");
out.println("                     <p class=\"client_text\">CO binds to hemoglobin in the blood more strongly than oxygen, reducing the blood's ability to carry oxygen to body tissues. This can lead to oxygen deprivation and result in symptoms like headaches, dizziness, and confusion.</p>");
out.println("                  </div>");
out.println("               </div>");
out.println("               <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images\\two.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Flu-Like Symptoms</h3>");
out.println("                     <p class=\"client_text\">Low to moderate CO exposure can cause flu-like symptoms, including nausea, vomiting, weakness, and chest pain, which may be misdiagnosed as other illnesses. </p>");
out.println("                  </div>");
out.println("               </div>");
out.println("               <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images\\three.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Severe Health Effects</h3>");
out.println("                     <p class=\"client_text\">High levels of CO exposure can lead to loss of consciousness, seizures, and even death. It is particularly dangerous in enclosed spaces with inadequate ventilation.</p>");
out.println("                  </div>");
out.println("               </div>");
out.println("            </div>");
out.println("         </div>");
out.println("      </div>");
out.println("      ");
out.println("     ");
out.println("      <!-- footer section end -->");
out.println("");
out.println("      <!-- Javascript files-->");
out.println("      <script src=\"js/jquery.min.js\"></script>");
out.println("      <script src=\"js/popper.min.js\"></script>");
out.println("      <script src=\"js/bootstrap.bundle.min.js\"></script>");
out.println("      <script src=\"js/jquery-3.0.0.min.js\"></script>");
out.println("      <script src=\"js/plugin.js\"></script>");
out.println("      <!-- sidebar -->");
out.println("      <script src=\"js/jquery.mCustomScrollbar.concat.min.js\"></script>");
out.println("      <script src=\"js/custom.js\"></script>");
out.println("   </body>");
out.println("</html>");
%>