<%
out.println("<!DOCTYPE html>");
out.println("<html>");
out.println("   <head>");
out.println("      <!-- basic -->");
out.println("      <meta charset=\"utf-8\">");
out.println("      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
out.println("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
out.println("      <!-- mobile metas -->");
out.println("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
out.println("      <meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1\">");
out.println("      <!-- site metas -->");
out.println("      <title>AQI</title>");
out.println("      <meta name=\"keywords\" content=\"\">");
out.println("      <meta name=\"description\" content=\"\">");
out.println("      <meta name=\"author\" content=\"\">");
out.println("      <!-- bootstrap css -->");
out.println("      <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">");
out.println("      <!-- style css -->");
out.println("      <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">");
out.println("      <!-- Responsive-->");
out.println("      <link rel=\"stylesheet\" href=\"css/responsive.css\">");
out.println("      <!-- fevicon -->");
out.println("      <link rel=\"icon\" href=\"images/fevicon.png\" type=\"image/gif\" />");
out.println("      <!-- font css -->");
out.println("      <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;800&display=swap\" rel=\"stylesheet\">");
out.println("      <!-- Scrollbar Custom CSS -->");
out.println("      <link rel=\"stylesheet\" href=\"css/jquery.mCustomScrollbar.min.css\">");
out.println("      <!-- Tweaks for older IEs-->");
out.println("      <link rel=\"stylesheet\" href=\"https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css\">");
out.println("   </head>");
out.println("   <body>");
out.println("      <div class=\"header_section\">");
out.println("         <div class=\"container-fluid\">");
out.println("            <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">");
out.println("               <a class=\"navbar-brand\" href=\"main.jsp\"><img src=\"images\\logo.png\"></a>");
out.println("               <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">");
out.println("               <span class=\"navbar-toggler-icon\"></span>");
out.println("               </button>");
out.println("               <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">");
out.println("                  <ul class=\"navbar-nav ml-auto\">");
out.println("                     <li class=\"nav-item active\">");
out.println("                        <a class=\"nav-link\" href=\"main.jsp\">Home</a>");
out.println("                     </li>");
out.println("                     <li class=\"nav-item\">");
out.println("                        <a class=\"nav-link\" href=\"Map.jsp\">Map</a>");
out.println("                     </li>");
out.println("<li class=\"nav-item dropdown\">");
out.println("    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">");
out.println("        States");
out.println("    </a>");
out.println("    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\" style=\"max-height: 350px; overflow-y: auto;\">");
out.println("        <a class=\"dropdown-item\" href=\"Ahmedabad.jsp\">Ahmedabad</a>");
out.println("        <a class=\"dropdown-item\" href=\"Aizawl.jsp\">Aizawl</a>");
out.println("        <a class=\"dropdown-item\" href=\"Amaravati.jsp\">Amaravati</a>");
out.println("        <a class=\"dropdown-item\" href=\"Amritsar.jsp\">Amritsar</a>");
out.println("        <a class=\"dropdown-item\" href=\"Bengaluru.jsp\">Bengaluru</a>");
out.println("        <a class=\"dropdown-item\" href=\"Bhopal.jsp\">Bhopal</a>");
out.println("        <a class=\"dropdown-item\" href=\"Brajrajnagar.jsp\">Brajrajnagar</a>");
out.println("        <a class=\"dropdown-item\" href=\"Chandigarh.jsp\">Chandigarh</a>");
out.println("        <a class=\"dropdown-item\" href=\"Chennai.jsp\">Chennai</a>");
out.println("        <a class=\"dropdown-item\" href=\"Coimbatore.jsp\">Coimbatore</a>");
out.println("        <a class=\"dropdown-item\" href=\"Delhi.jsp\">Delhi</a>");
out.println("        <a class=\"dropdown-item\" href=\"Ernakulam.jsp\">Ernakulam</a>");
out.println("        <a class=\"dropdown-item\" href=\"Gurugram.jsp\">Gurugram</a>");
out.println("        <a class=\"dropdown-item\" href=\"Guwahati.jsp\">Guwahati</a>");
out.println("        <a class=\"dropdown-item\" href=\"Hyderabad.jsp\">Hyderabad</a>");
out.println("        <a class=\"dropdown-item\" href=\"Jaipur.jsp\">Jaipur</a>");
out.println("        <a class=\"dropdown-item\" href=\"Jorapokhar.jsp\">Jorapokhar</a>");
out.println("        <a class=\"dropdown-item\" href=\"Kochi.jsp\">Kochi</a>");
out.println("        <a class=\"dropdown-item\" href=\"Kolkata.jsp\">Kolkata</a>");
out.println("        <a class=\"dropdown-item\" href=\"Lucknow.jsp\">Lucknow</a>");
out.println("        <a class=\"dropdown-item\" href=\"Mumbai.jsp\">Mumbai</a>");
out.println("        <a class=\"dropdown-item\" href=\"Patna.jsp\">Patna</a>");
out.println("        <a class=\"dropdown-item\" href=\"Shillong.jsp\">Shillong</a>");
out.println("        <a class=\"dropdown-item\" href=\"Talcher.jsp\">Talcher</a>");
out.println("        <a class=\"dropdown-item\" href=\"Thiruvananthapuram.jsp\">Thiruvananthapuram</a>");
out.println("        <a class=\"dropdown-item\" href=\"Visakhapatnam.jsp\">Visakhapatnam</a>");
out.println("        <!-- Add more states as needed -->");
out.println("    </div>");
out.println("</li>");
out.println("                  </ul>");
out.println("                  <form class=\"form-inline my-2 my-lg-0\">");
out.println("                     <div class=\"login_bt\">");
out.println("                        <ul>");
out.println("                           <li><a href=\"#\"><i class=\"fa fa-search\" aria-hidden=\"true\"></i></a></li>");
out.println("                        </ul>");
out.println("                     </div>");
out.println("                  </form>");
out.println("               </div>");
out.println("            </nav>");
out.println("         </div>");
out.println("         <!-- banner section start --> ");
out.println("         <div class=\"banner_section layout_padding\">");
out.println("            <div class=\"container\">");
out.println("               <div id=\"banner_slider\" class=\"carousel slide\" data-ride=\"carousel\">");
out.println("                  <div class=\"carousel-inner\">");
out.println("                     <div class=\"carousel-item active\">");
out.println("                        <div class=\"row\">");
out.println("                           <div class=\"col-md-6\">");
out.println("                              <div class=\"banner_img\"><img src=\"images/banner-img.png\"></div>");
out.println("                           </div>");
out.println("                           <div class=\"col-md-6\">");
out.println("                              <div class=\"banner_taital_main\">");
out.println("                                 <h1 class=\"banner_taital\">AQI</h1>");
out.println("                                 <h5 class=\"tasty_text\">Air Quality Index</h5>");
out.println("                                 <p class=\"banner_text\">Breath Easy Breath Safe </p>");
out.println("                               ");
out.println("                              </div>");
out.println("                           </div>");
out.println("                        </div>");
out.println("                     </div>");
out.println("                     <div class=\"carousel-item\">");
out.println("                        <div class=\"row\">");
out.println("                           <div class=\"col-md-6\">");
out.println("                              <div class=\"banner_img\"><img src=\"images/banner-img.png\"></div>");
out.println("                           </div>");
out.println("                           <div class=\"col-md-6\">");
out.println("                              <div class=\"banner_taital_main\">");
out.println("                                 <h1 class=\"banner_taital\">AQI</h1>");
out.println("                                 <h5 class=\"tasty_text\">High AQI means poor air</h5>");
out.println("                                 <p class=\"banner_text\">High AQI signifies poor air quality with health and environmental risks,prompting precautions like limiting outdoor activities.</p>");
out.println("                              </div>");
out.println("                           </div>");
out.println("                        </div>");
out.println("                     </div>");
out.println("                     <div class=\"carousel-item\">");
out.println("                        <div class=\"row\">");
out.println("                           <div class=\"col-md-6\">");
out.println("                              <div class=\"banner_img\"><img src=\"images/banner-img.png\"></div>");
out.println("                           </div>");
out.println("                           <div class=\"col-md-6\">");
out.println("                              <div class=\"banner_taital_main\">");
out.println("                                 <h1 class=\"banner_taital\">AQI</h1>");
out.println("                                 <h5 class=\"tasty_text\">AQI indicates air pollution levels</h5>");
out.println("                                 <p class=\"banner_text\">The Air Quality Index (AQI) indicates air pollution levels and helps people assess their local air quality</p>");
out.println("                              </div>");
out.println("                           </div>");
out.println("                        </div>");
out.println("                     </div>");
out.println("                  </div>");
out.println("                  <a class=\"carousel-control-prev\" href=\"#banner_slider\" role=\"button\" data-slide=\"prev\">");
out.println("                  <i class=\"fa fa-arrow-left\"></i>");
out.println("                  </a>");
out.println("                  <a class=\"carousel-control-next\" href=\"#banner_slider\" role=\"button\" data-slide=\"next\">");
out.println("                  <i class=\"fa fa-arrow-right\"></i>");
out.println("                  </a>");
out.println("               </div>");
out.println("            </div>");
out.println("         </div>");
out.println("         <!-- banner section end -->");
out.println("      </div>");
out.println("      <!-- header section end -->");
out.println("      <!-- coffee section start -->");
out.println("      <div class=\"coffee_section layout_padding\">");
out.println("         <div class=\"container\">");
out.println("            <div class=\"row\">");
out.println("               <h1 class=\"coffee_taital\">List of Parameters</h1>");
out.println("               <div class=\"bulit_icon\"><img src=\"images/bulit-icon.png\"></div>");
out.println("            </div>");
out.println("         </div>");
out.println("         <div class=\"coffee_section_2\">");
out.println("            <div id=\"main_slider\" class=\"carousel slide\" data-ride=\"carousel\">");
out.println("               <div class=\"carousel-inner\">");
out.println("                  <div class=\"carousel-item active\">");
out.println("                     <div class=\"container-fluid\">");
out.println("                        <div class=\"row\">");
out.println("                           <div class=\"col-lg-3 col-md-6\">");
out.println("                              <div class=\"coffee_img\"><img src=\"images\\image-1.png\" ></div>");
out.println("                              <h3 class=\"types_text\">PM <sub>2.5</sub></h3>");
out.println("                              <p class=\"looking_text\">Airborne particulate matter 2.5 microns</p>");
out.println("                              <div class=\"read_bt\"><a href=\"pm2.5.jsp\">Read More</a></div>");
out.println("                           </div>");
out.println("                           <div class=\"col-lg-3 col-md-6\">");
out.println("                              <div class=\"coffee_img\"><img src=\"images\\image-2.jpg\"></div>");
out.println("                              <h3 class=\"types_text\">PM <sub>10</sub></h3>");
out.println("                              <p class=\"looking_text\">Airborne particulate matter 10 microns</p>");
out.println("                              <div class=\"read_bt\"><a href=\"pm 10.jsp\">Read More</a></div>");
out.println("                           </div>");
out.println("                           <div class=\"col-lg-3 col-md-6\">");
out.println("                              <div class=\"coffee_img\"><img src=\"images\\image-3.jpg\"></div>");
out.println("                              <h3 class=\"types_text\">NO<sub>2</sub></h3>");
out.println("                              <p class=\"looking_text\">Air pollutant, reddish-brown, nitrogen dioxide gas</p>");
out.println("                              <div class=\"read_bt\"><a href=\"no2.jsp\">Read More</a></div>");
out.println("                           </div>");
out.println("                           <div class=\"col-lg-3 col-md-6\">");
out.println("                              <div class=\"coffee_img\"><img src=\"images\\image-4.jpeg\"></div>");
out.println("                              <h3 class=\"types_text\">SO<sub>2</sub></h3>");
out.println("                              <p class=\"looking_text\">Sulfur dioxide, pungent gas, air pollutant</p>");
out.println("                              <div class=\"read_bt\"><a href=\"so2.jsp\">Read More</a></div>");
out.println("                           </div>");
out.println("                        </div>");
out.println("                     </div>");
out.println("                  </div>");
out.println("                  <div class=\"carousel-item\">");
out.println("                     <div class=\"container-fluid\">");
out.println("                        <div class=\"row\">");
out.println("                           <div class=\"col-lg-3 col-md-6\">");
out.println("                              <div class=\"coffee_img\"><img src=\"images\\image-5.jpg\"></div>");
out.println("                              <h3 class=\"types_text\">CO</h3>");
out.println("                              <p class=\"looking_text\">Carbon monoxide, colorless, odorless, poisonous gas</p>");
out.println("                              <div class=\"read_bt\"><a href=\"co.jsp\">Read More</a></div>");
out.println("                           </div>");
out.println("                           <div class=\"col-lg-3 col-md-6\">");
out.println("                              <div class=\"coffee_img\"><img src=\"images\\image-6.jpg\"></div>");
out.println("                              <h3 class=\"types_text\">O<sub>3</sub></h3>");
out.println("                              <p class=\"looking_text\">Ozone, beneficial stratospheric layer gas</p>");
out.println("                              <div class=\"read_bt\"><a href=\"o3.jsp\">Read More</a></div>");
out.println("                           </div>");
out.println("                           <div class=\"col-lg-3 col-md-6\">");
out.println("                              <div class=\"coffee_img\"><img src=\"images\\image-7.jpg\"></div>");
out.println("                              <h3 class=\"types_text\">NH<sub>3</sub></h3>");
out.println("                              <p class=\"looking_text\">Ammonia, pungent-smelling, toxic gas</p>");
out.println("                              <div class=\"read_bt\"><a href=\"nh3.jsp\">Read More</a></div>");
out.println("                           </div>");
out.println("                           <div class=\"col-lg-3 col-md-6\">");
out.println("                              <div class=\"coffee_img\"><img src=\"images\\image-9.jpg\"></div>");
out.println("                              <h3 class=\"types_text\">Pb</h3>");
out.println("                              <p class=\"looking_text\">Lead (Pb), heavy metal, toxic substance</p>");
out.println("                              <div class=\"read_bt\"><a href=\"pb.jsp\">Read More</a></div>");
out.println("                           </div>");
out.println("                        </div>");
out.println("                     </div>");
out.println("                  </div>");
out.println("                  <div class=\"carousel-item\">");
out.println("                     <div class=\"container-fluid\">");
out.println("                        <div class=\"row\">");
out.println("                           <div class=\"col-lg-3 col-md-6\">");
out.println("                              <div class=\"coffee_img\"><img src=\"images\\image-10.jpg\"></div>");
out.println("                              <h3 class=\"types_text\">TOLUENE</h3>");
out.println("                              <p class=\"looking_text\">Aromatic hydrocarbon, solvent, sweet-smelling</p>");
out.println("                              <div class=\"read_bt\"><a href=\"toluene.jsp\">Read More</a></div>");
out.println("                           </div>");
out.println("                           <div class=\"col-lg-3 col-md-6\">");
out.println("                              <div class=\"coffee_img\"><img src=\"images\\image-11.jpg\"></div>");
out.println("                              <h3 class=\"types_text\">BENZENE</h3>");
out.println("                              <p class=\"looking_text\">Aromatic hydrocarbon, flammable liquid</p>");
out.println("                              <div class=\"read_bt\"><a href=\"Benzene.jsp\">Read More</a></div>");
out.println("                           </div>");
out.println("                           <div class=\"col-lg-3 col-md-6\">");
out.println("                              <div class=\"coffee_img\"><img src=\"images\\image-12.jpg\"></div>");
out.println("                              <h3 class=\"types_text\">XYLENE</h3>");
out.println("                              <p class=\"looking_text\">Aromatic hydrocarbon, solvent, flammable</p>");
out.println("                              <div class=\"read_bt\"><a href=\"xylene.jsp\">Read More</a></div>");
out.println("                           </div>");
out.println("                           <div class=\"col-lg-3 col-md-6\">");
out.println("                              <div class=\"coffee_img\"><img src=\"images\\image -13.jpg\"></div>");
out.println("                              <h3 class=\"types_text\">NO<sub>x</sub></h3>");
out.println("                              <p class=\"looking_text\">NOx, nitrogen oxides, air pollutant components</p>");
out.println("                              <div class=\"read_bt\"><a href=\"nox.jsp\">Read More</a></div>");
out.println("                           </div>");
out.println("                        </div>");
out.println("                     </div>");
out.println("                  </div>");
out.println("               </div>");
out.println("               <a class=\"carousel-control-prev\" href=\"#main_slider\" role=\"button\" data-slide=\"prev\">");
out.println("               <i class=\"fa fa-arrow-left\"></i>");
out.println("               </a>");
out.println("               <a class=\"carousel-control-next\" href=\"#main_slider\" role=\"button\" data-slide=\"next\">");
out.println("               <i class=\"fa fa-arrow-right\"></i>");
out.println("               </a>");
out.println("            </div>");
out.println("         </div>");
out.println("      </div>");
out.println("      <!-- coffee section end -->");
out.println("      <!-- about section start -->");
out.println("      <div class=\"about_section layout_padding\">");
out.println("         <div class=\"container\">");
out.println("            <div class=\"row\">");
out.println("               <div class=\"col-md-12\">");
out.println("                  <h1 class=\"about_taital\">About AQI</h1>");
out.println("                  <div class=\"bulit_icon\"><img src=\"images/bulit-icon.png\"></div>");
out.println("               </div>");
out.println("            </div>");
out.println("            <div class=\"about_section_2 layout_padding\">");
out.println("               <div class=\"image_iman\"><img src=\"images/about-img.png\" class=\"about_img\"></div>");
out.println("               <div class=\"about_taital_box\">");
out.println("                  <h1 class=\"about_taital_1\">Check AQI for air quality...</h1>");
out.println("                  <p class=\" about_text\">The Air Quality Index (AQI) is a standardized system used to measure and communicate the quality of the air in a specific location. It assesses the concentration of key air pollutants, including ground-level ozone, particulate matter, carbon monoxide, sulfur dioxide, and nitrogen dioxide. The AQI provides a numerical value and corresponding color code to indicate air quality levels, ranging from \"Good\" to \"Hazardous.\" It serves as a vital tool for public awareness and decision-making regarding outdoor activities and health protection.</p>");
out.println("                  <div class=\"readmore_btn\"><a href=\"#\">Read More</a></div>");
out.println("               </div>");
out.println("            </div>");
out.println("         </div>");
out.println("      </div>");
out.println("      <!-- about section end -->");
out.println("      <!-- client section start -->");
out.println("      <div class=\"client_section layout_padding\">");
out.println("         <div class=\"container\">");
out.println("            <div class=\"row\">");
out.println("               <div class=\"col-md-12\">");
out.println("                  <h1 class=\"about_taital\">Air Quality Standards</h1>");
out.println("                  <div class=\"bulit_icon\"><img src=\"images/bulit-icon.png\"></div>");
out.println("               </div>");
out.println("            </div>");
out.println("            <div class=\"client_section_2\">");
out.println("               <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images/client-img1.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Good</h3>");
out.println("                     <p class=\"client_text\">AQI Range of 0-50 is considered \"Good.\" This means the air quality is healthy, and it poses little to no risk, benefiting overall well-being and reducing health concerns related to air pollution. </p>");
out.println("                  </div>");
out.println("               </div>");
out.println("               <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images/client-img3.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Moderate</h3>");
out.println("                     <p class=\"client_text\">An AQI range of 51-100 is considered \"Moderate.\" This suggests that the air quality is acceptable, with a moderate health concern for a very small number of individuals who are unusually sensitive to air pollution. It indicates that the general public is unlikely to be significantly affected, but some caution may be needed for outdoor activities. </p>");
out.println("                  </div>");
out.println("               </div>");
out.println("               <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images/client-img2.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Unhealthy for Sensitive Groups</h3>");
out.println("                     <p class=\"client_text\">An AQI range of 101-150 is considered \"Unhealthy for Sensitive Groups.\" This means air quality may affect individuals with respiratory or heart conditions, but the general public is not likely to be affected. It indicates a moderate health concern for sensitive individuals. </p>");
out.println("                  </div>");
out.println("               </div>");
out.println(" <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images/unhealthy.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Unhealthy</h3>");
out.println("                     <p class=\"client_text\">An AQI range of 151-200 is considered \"Unhealthy.\" This indicates that the air quality is harmful to health, with everyone likely to be affected. It poses a higher risk of health concerns related to air pollution, and individuals should limit outdoor activities and take precautions. </p>");
out.println("                  </div>");
out.println("               </div>");
out.println(" <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images/veryunhealthy.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Very Unhealthy</h3>");
out.println("                     <p class=\"client_text\">An AQI range of 201-300 is considered \"Very Unhealthy.\" This signifies that the air quality is severely polluted, and it poses a significant risk to health. People should avoid outdoor activities, and even those with no sensitivities may experience health effects. </p>");
out.println("                  </div>");
out.println("               </div>");
out.println(" <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images/Hazardous.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Hazardous</h3>");
out.println("                     <p class=\"client_text\">An AQI range of 301-500 is considered \"Hazardous.\" This signifies that the air quality is extremely poor, posing a severe risk to health. Prolonged exposure to such conditions can lead to immediate and significant health concerns, requiring urgent protective measures and avoidance of outdoor activities. </p>");
out.println("                  </div>");
out.println("               </div>");
out.println("            </div>");
out.println("         </div>");
out.println("      </div>");
out.println("      <!-- contact section end -->");
out.println("<div class=\"footer_section layout_padding\">");
out.println("         <div class=\"container\">");
out.println("            <div class=\"row\">");
out.println("               <div class=\"col-md-12\">");
out.println("                  <h1 class=\"address_text\"></h1>");
out.println("                  <p class=\"footer_text\">''Because awareness is as present in our lives as the air we breathe, we can access it anywhere, anytime''");
out.println("- Mingyur Rinpoche </p>");
out.println("                  <div class=\"location_text\">");
out.println("                     <ul>");
out.println("                        <li>");
out.println("                           <a href=\"#\">");
out.println("                           <i aria-hidden=\"true\"></i><span class=\"padding_left_10\">''Breathe and let be.''</span>");
out.println("                           </a>");
out.println("                        </li>");
out.println("                        <li>");
out.println("                           <a href=\"#\">");
out.println("                           <i  aria-hidden=\"true\"></i><span class=\"padding_left_10\"></span>");
out.println("                           </a>");
out.println("                        </li>");
out.println("                     </ul>");
out.println("                  </div>");
out.println("               </div>");
out.println("            </div>");
out.println("         </div>");
out.println("      </div>");
out.println("");
out.println("      ");
out.println("      <!-- Javascript files-->");
out.println("      <script src=\"js/jquery.min.js\"></script>");
out.println("      <script src=\"js/popper.min.js\"></script>");
out.println("      <script src=\"js/bootstrap.bundle.min.js\"></script>");
out.println("      <script src=\"js/jquery-3.0.0.min.js\"></script>");
out.println("      <script src=\"js/plugin.js\"></script>");
out.println("      <!-- sidebar -->");
out.println("      <script src=\"js/jquery.mCustomScrollbar.concat.min.js\"></script>");
out.println("      <script src=\"js/custom.js\"></script>");
out.println("   </body>");
out.println("</html>");
%>