<%
out.println("<!DOCTYPE html>");
out.println("<html>");
out.println("   <head>");
out.println("      <!-- basic -->");
out.println("      <meta charset=\"utf-8\">");
out.println("      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
out.println("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
out.println("      <!-- mobile metas -->");
out.println("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
out.println("      <meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1\">");
out.println("      <!-- site metas -->");
out.println("      <title>Pb</title>");
out.println("      <meta name=\"keywords\" content=\"\">");
out.println("      <meta name=\"description\" content=\"\">");
out.println("      <meta name=\"author\" content=\"\">");
out.println("      <!-- bootstrap css -->");
out.println("      <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">");
out.println("      <!-- style css -->");
out.println("      <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">");
out.println("      <!-- Responsive-->");
out.println("      <link rel=\"stylesheet\" href=\"css/responsive.css\">");
out.println("      <!-- fevicon -->");
out.println("      <link rel=\"icon\" href=\"images/fevicon.png\" type=\"image/gif\" />");
out.println("      <!-- font css -->");
out.println("      <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;800&display=swap\" rel=\"stylesheet\">");
out.println("      <!-- Scrollbar Custom CSS -->");
out.println("      <link rel=\"stylesheet\" href=\"css/jquery.mCustomScrollbar.min.css\">");
out.println("      <!-- Tweaks for older IEs-->");
out.println("      <link rel=\"stylesheet\" href=\"https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css\">");
out.println("   </head>");
out.println("   <body>");
out.println("      <div class=\"header_section header_bg\">");
out.println("         <div class=\"container-fluid\">");
out.println("            <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">");
out.println("               <a class=\"navbar-brand\"href=\"main.jsp\"><img src=\"images/logo.png\"></a>");
out.println("               <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">");
out.println("               <span class=\"navbar-toggler-icon\"></span>");
out.println("               </button>");
out.println("               <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">");
out.println("                  <ul class=\"navbar-nav ml-auto\">");
out.println("                     <li class=\"nav-item\">");
out.println("                        <a class=\"nav-link\" href=\"main.jsp\">Home</a>");
out.println("                     </li>");
out.println("                     <li class=\"nav-item\">");
out.println("                        <a class=\"nav-link\" href=\"Map.jsp\">Map</a>");
out.println("                     </li>");
out.println("                     <li class=\"nav-item\">");
out.println("                        <a class=\"nav-link\" href=\"Report.jsp\">Report</a>");
out.println("                     </li>");
out.println("                  </ul>");
out.println("                  <form class=\"form-inline my-2 my-lg-0\">");
out.println("                     <div class=\"login_bt\">");
out.println("                        <ul>");
out.println("                           ");
out.println("                           <li><a href=\"#\"><i class=\"fa fa-search\" aria-hidden=\"true\"></i></a></li>");
out.println("                        </ul>");
out.println("                     </div>");
out.println("                  </form>");
out.println("               </div>");
out.println("            </nav>");
out.println("         </div>");
out.println("      </div>");
out.println("      <!-- header section end -->");
out.println("      <!-- blog section start -->");
out.println("      <div class=\"blog_section layout_padding\">");
out.println("         <div class=\"container\">");
out.println("            <div class=\"row\">");
out.println("               <div class=\"col-md-12\">");
out.println("                  <h1 class=\"about_taital\">Pb</h1>");
out.println("                  <div class=\"bulit_icon\"><img src=\"images/bulit-icon.png\"></div>");
out.println("               </div>");
out.println("            </div>");
out.println("            <div class=\"blog_section_2\">");
out.println("               <div class=\"row\">");
out.println("                  <div class=\"col-md-6\">");
out.println("                     <div class=\"blog_box\">");
out.println("                        <div class=\"blog_img\"><img src=\"images\\pm2.5.webp\"></div>");
out.println("                        <h4 class=\"date_text\">#7</h4>");
out.println("                        <h4 class=\"prep_text\">Pb</h4>");
out.println("                        <p class=\"lorem_text\">Pb is the chemical symbol for lead, a heavy metal known for its toxic effects on human health and the environment</p>");
out.println("                     </div>");
out.println("                  </div>");
out.println("                  <div class=\"col-md-6\">");
out.println("                     <div class=\"blog_box\">");
out.println("                        <div class=\"blog_img\"></div>");
out.println("                        <h4 class=\"prep_text\">Pb</h4>");
out.println("                        <p class=\"lorem_text\">");
out.println("Pb is the chemical symbol for lead, a heavy metal that has been known for centuries and has both beneficial and harmful applications. Lead has been used historically in various industries, such as in the production of lead-acid batteries, plumbing pipes, and as an additive in gasoline. However, its harmful effects on human health and the environment have been a cause for concern. Lead exposure can result in lead poisoning, leading to a range of health issues, especially in children, including developmental delays, learning disabilities, and behavioral problems. Even low levels of lead exposure can have detrimental effects. Recognizing these risks, lead has been phased out from many applications, including gasoline and plumbing, and strict regulations are in place to limit its presence in consumer products. Efforts to reduce lead exposure and its harmful effects continue to be a priority in public health and environmental protection.</p>");
out.println("                     </div>");
out.println("                  </div>");
out.println("               </div>");
out.println("            </div>");
out.println("         </div>");
out.println("      </div>");
out.println("<!-- about section end -->");
out.println("      <!-- client section start -->");
out.println("      <div class=\"client_section layout_padding\">");
out.println("         <div class=\"container\">");
out.println("            <div class=\"row\">");
out.println("               <div class=\"col-md-12\">");
out.println("                  <h1 class=\"about_taital\">Harm Full Effects</h1>");
out.println("                  <div class=\"bulit_icon\"><img src=\"images/bulit-icon.png\"></div>");
out.println("               </div>");
out.println("            </div>");
out.println("            <div class=\"client_section_2\">");
out.println("               <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images\\one.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Hypertension</h3>");
out.println("                     <p class=\"client_text\">There is evidence that lead exposure can contribute to high blood pressure, increasing the risk of cardiovascular problems. </p>");
out.println("                  </div>");
out.println("               </div>");
out.println("               <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images\\two.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Neurological Damage</h3>");
out.println("                     <p class=\"client_text\"> Lead is particularly toxic to the nervous system, and exposure, especially in children, can result in cognitive impairment, developmental delays, learning disabilities, and behavioral problems.</p>");
out.println("                  </div>");
out.println("               </div>");
out.println("               <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images\\three.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Gastrointestinal Distress</h3>");
out.println("                     <p class=\"client_text\"> Ingesting lead-contaminated substances can cause abdominal pain, nausea, vomiting, and other gastrointestinal problems.</p>");
out.println("                  </div>");
out.println("               </div>");
out.println("            </div>");
out.println("         </div>");
out.println("      </div>");
out.println("      ");
out.println("     ");
out.println("      <!-- footer section end -->");
out.println("");
out.println("      <!-- Javascript files-->");
out.println("      <script src=\"js/jquery.min.js\"></script>");
out.println("      <script src=\"js/popper.min.js\"></script>");
out.println("      <script src=\"js/bootstrap.bundle.min.js\"></script>");
out.println("      <script src=\"js/jquery-3.0.0.min.js\"></script>");
out.println("      <script src=\"js/plugin.js\"></script>");
out.println("      <!-- sidebar -->");
out.println("      <script src=\"js/jquery.mCustomScrollbar.concat.min.js\"></script>");
out.println("      <script src=\"js/custom.js\"></script>");
out.println("   </body>");
out.println("</html>");
%>