<%
out.println("<!DOCTYPE html>");
out.println("<html>");
out.println("   <head>");
out.println("      <!-- basic -->");
out.println("      <meta charset=\"utf-8\">");
out.println("      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
out.println("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
out.println("      <!-- mobile metas -->");
out.println("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
out.println("      <meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1\">");
out.println("      <!-- site metas -->");
out.println("      <title>PM<sub>2.5</sub>2.5</title>");
out.println("      <meta name=\"keywords\" content=\"\">");
out.println("      <meta name=\"description\" content=\"\">");
out.println("      <meta name=\"author\" content=\"\">");
out.println("      <!-- bootstrap css -->");
out.println("      <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">");
out.println("      <!-- style css -->");
out.println("      <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">");
out.println("      <!-- Responsive-->");
out.println("      <link rel=\"stylesheet\" href=\"css/responsive.css\">");
out.println("      <!-- fevicon -->");
out.println("      <link rel=\"icon\" href=\"images/fevicon.png\" type=\"image/gif\" />");
out.println("      <!-- font css -->");
out.println("      <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;800&display=swap\" rel=\"stylesheet\">");
out.println("      <!-- Scrollbar Custom CSS -->");
out.println("      <link rel=\"stylesheet\" href=\"css/jquery.mCustomScrollbar.min.css\">");
out.println("      <!-- Tweaks for older IEs-->");
out.println("      <link rel=\"stylesheet\" href=\"https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css\">");
out.println("   </head>");
out.println("   <body>");
out.println("      <div class=\"header_section header_bg\">");
out.println("         <div class=\"container-fluid\">");
out.println("            <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">");
out.println("               <a class=\"navbar-brand\"href=\"main.jsp\"><img src=\"images/logo.png\"></a>");
out.println("               <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">");
out.println("               <span class=\"navbar-toggler-icon\"></span>");
out.println("               </button>");
out.println("               <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">");
out.println("                  <ul class=\"navbar-nav ml-auto\">");
out.println("                     <li class=\"nav-item\">");
out.println("                        <a class=\"nav-link\" href=\"main.jsp\">Home</a>");
out.println("                     </li>");
out.println("                     <li class=\"nav-item\">");
out.println("                        <a class=\"nav-link\" href=\"Map.jsp\">Map</a>");
out.println("                     </li>");
out.println("                     <li class=\"nav-item\">");
out.println("                        <a class=\"nav-link\" href=\"Report.jsp\">Report</a>");
out.println("                     </li>");
out.println("                  </ul>");
out.println("                  <form class=\"form-inline my-2 my-lg-0\">");
out.println("                     <div class=\"login_bt\">");
out.println("                        <ul>");
out.println("                           ");
out.println("                           <li><a href=\"#\"><i class=\"fa fa-search\" aria-hidden=\"true\"></i></a></li>");
out.println("                        </ul>");
out.println("                     </div>");
out.println("                  </form>");
out.println("               </div>");
out.println("            </nav>");
out.println("         </div>");
out.println("      </div>");
out.println("      <!-- header section end -->");
out.println("      <!-- blog section start -->");
out.println("      <div class=\"blog_section layout_padding\">");
out.println("         <div class=\"container\">");
out.println("            <div class=\"row\">");
out.println("               <div class=\"col-md-12\">");
out.println("                  <h1 class=\"about_taital\">PM-2.5</h1>");
out.println("                  <div class=\"bulit_icon\"><img src=\"images/bulit-icon.png\"></div>");
out.println("               </div>");
out.println("            </div>");
out.println("            <div class=\"blog_section_2\">");
out.println("               <div class=\"row\">");
out.println("                  <div class=\"col-md-6\">");
out.println("                     <div class=\"blog_box\">");
out.println("                        <div class=\"blog_img\"><img src=\"images\\pm2.5.webp\"></div>");
out.println("                        <h4 class=\"date_text\">#1</h4>");
out.println("                        <h4 class=\"prep_text\">PM<sub>2.5</sub>2.5</h4>");
out.println("                        <p class=\"lorem_text\">\"Particulate Matter 2.5\",referring to fine particulate matter with a diameter of 2.5 micrometers or smaller</p>");
out.println("                     </div>");
out.println("                  </div>");
out.println("                  <div class=\"col-md-6\">");
out.println("                     <div class=\"blog_box\">");
out.println("                        <div class=\"blog_img\"></div>");
out.println("                        <h4 class=\"prep_text\">Particulate Matter 2.5...</h4>");
out.println("                        <p class=\"lorem_text\">");
out.println("PM<sub>2.5</sub>, which stands for Particulate Matter 2.5, is a critical air quality parameter that refers to tiny solid particles and liquid droplets with a diameter of 2.5 micrometers or smaller. These minuscule particles can come from a variety of sources, including vehicle emissions, industrial activities, construction, and natural processes like dust and wildfires. PM<sub>2.5</sub> is of particular concern due to its ability to penetrate deep into the respiratory system when inhaled. Because of its small size, it can bypass the body's natural defense mechanisms and enter the lungs and even the bloodstream, potentially causing a range of health problems. Long-term exposure to elevated levels of PM<sub>2.5</sub> has been linked to respiratory diseases, cardiovascular issues, and even premature death. Monitoring and controlling PM<sub>2.5</sub> pollution is crucial for safeguarding public health and maintaining air quality standards.</p>");
out.println("                     </div>");
out.println("                  </div>");
out.println("               </div>");
out.println("            </div>");
out.println("         </div>");
out.println("      </div>");
out.println("<!-- about section end -->");
out.println("      <!-- client section start -->");
out.println("      <div class=\"client_section layout_padding\">");
out.println("         <div class=\"container\">");
out.println("            <div class=\"row\">");
out.println("               <div class=\"col-md-12\">");
out.println("                  <h1 class=\"about_taital\">Harm Full Effects</h1>");
out.println("                  <div class=\"bulit_icon\"><img src=\"images/bulit-icon.png\"></div>");
out.println("               </div>");
out.println("            </div>");
out.println("            <div class=\"client_section_2\">");
out.println("               <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images\\one.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Respiratory Problems</h3>");
out.println("                     <p class=\"client_text\">PM<sub>2.5</sub> can penetrate deep into the lungs and even enter the bloodstream, causing respiratory problems such as coughing, wheezing, and exacerbating conditions like asthma, bronchitis, and chronic obstructive pulmonary disease (COPD).</p>");
out.println("                  </div>");
out.println("               </div>");
out.println("               <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images\\two.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Cardiovascular Issues</h3>");
out.println("                     <p class=\"client_text\">PM<sub>2.5</sub> exposure is associated with an increased risk of heart attacks, strokes, and other cardiovascular diseases. It can lead to inflammation in blood vessels and affect the functioning of the heart. </p>");
out.println("                  </div>");
out.println("               </div>");
out.println("               <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images\\three.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Environmental Impact</h3>");
out.println("                     <p class=\"client_text\"> PM<sub>2.5</sub> can also have detrimental effects on the environment. It can contribute to acid rain, harm wildlife, and damage crops and forests. It also reduces visibility and affects air quality. </p>");
out.println("                  </div>");
out.println("               </div>");
out.println("            </div>");
out.println("         </div>");
out.println("      </div>");
out.println("      ");
out.println("     ");
out.println("      <!-- footer section end -->");
out.println("");
out.println("      <!-- Javascript files-->");
out.println("      <script src=\"js/jquery.min.js\"></script>");
out.println("      <script src=\"js/popper.min.js\"></script>");
out.println("      <script src=\"js/bootstrap.bundle.min.js\"></script>");
out.println("      <script src=\"js/jquery-3.0.0.min.js\"></script>");
out.println("      <script src=\"js/plugin.js\"></script>");
out.println("      <!-- sidebar -->");
out.println("      <script src=\"js/jquery.mCustomScrollbar.concat.min.js\"></script>");
out.println("      <script src=\"js/custom.js\"></script>");
out.println("   </body>");
out.println("</html>");
%>