<%
out.println("<!DOCTYPE html>");
out.println("<html>");
out.println("   <head>");
out.println("      <!-- basic -->");
out.println("      <meta charset=\"utf-8\">");
out.println("      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
out.println("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
out.println("      <!-- mobile metas -->");
out.println("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
out.println("      <meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1\">");
out.println("      <!-- site metas -->");
out.println("      <title>Xylene</title>");
out.println("      <meta name=\"keywords\" content=\"\">");
out.println("      <meta name=\"description\" content=\"\">");
out.println("      <meta name=\"author\" content=\"\">");
out.println("      <!-- bootstrap css -->");
out.println("      <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">");
out.println("      <!-- style css -->");
out.println("      <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">");
out.println("      <!-- Responsive-->");
out.println("      <link rel=\"stylesheet\" href=\"css/responsive.css\">");
out.println("      <!-- fevicon -->");
out.println("      <link rel=\"icon\" href=\"images/fevicon.png\" type=\"image/gif\" />");
out.println("      <!-- font css -->");
out.println("      <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;800&display=swap\" rel=\"stylesheet\">");
out.println("      <!-- Scrollbar Custom CSS -->");
out.println("      <link rel=\"stylesheet\" href=\"css/jquery.mCustomScrollbar.min.css\">");
out.println("      <!-- Tweaks for older IEs-->");
out.println("      <link rel=\"stylesheet\" href=\"https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css\">");
out.println("   </head>");
out.println("   <body>");
out.println("      <div class=\"header_section header_bg\">");
out.println("         <div class=\"container-fluid\">");
out.println("            <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">");
out.println("               <a class=\"navbar-brand\"href=\"main.jsp\"><img src=\"images/logo.png\"></a>");
out.println("               <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">");
out.println("               <span class=\"navbar-toggler-icon\"></span>");
out.println("               </button>");
out.println("               <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">");
out.println("                  <ul class=\"navbar-nav ml-auto\">");
out.println("                     <li class=\"nav-item\">");
out.println("                        <a class=\"nav-link\" href=\"main.jsp\">Home</a>");
out.println("                     </li>");
out.println("                     <li class=\"nav-item\">");
out.println("                        <a class=\"nav-link\" href=\"Map.jsp\">Map</a>");
out.println("                     </li>");
out.println("                     <li class=\"nav-item\">");
out.println("                        <a class=\"nav-link\" href=\"Report.jsp\">Report</a>");
out.println("                     </li>");
out.println("                  </ul>");
out.println("                  <form class=\"form-inline my-2 my-lg-0\">");
out.println("                     <div class=\"login_bt\">");
out.println("                        <ul>");
out.println("                           ");
out.println("                           <li><a href=\"#\"><i class=\"fa fa-search\" aria-hidden=\"true\"></i></a></li>");
out.println("                        </ul>");
out.println("                     </div>");
out.println("                  </form>");
out.println("               </div>");
out.println("            </nav>");
out.println("         </div>");
out.println("      </div>");
out.println("      <!-- header section end -->");
out.println("      <!-- blog section start -->");
out.println("      <div class=\"blog_section layout_padding\">");
out.println("         <div class=\"container\">");
out.println("            <div class=\"row\">");
out.println("               <div class=\"col-md-12\">");
out.println("                  <h1 class=\"about_taital\">XYLENE</h1>");
out.println("                  <div class=\"bulit_icon\"><img src=\"images/bulit-icon.png\"></div>");
out.println("               </div>");
out.println("            </div>");
out.println("            <div class=\"blog_section_2\">");
out.println("               <div class=\"row\">");
out.println("                  <div class=\"col-md-6\">");
out.println("                     <div class=\"blog_box\">");
out.println("                        <div class=\"blog_img\"><img src=\"images\\pm2.5.webp\"></div>");
out.println("                        <h4 class=\"date_text\">#1</h4>");
out.println("                        <h4 class=\"prep_text\">Xylene</h4>");
out.println("                        <p class=\"lorem_text\">Xylene, a volatile organic compound found in vehicle emissions and industrial processes, contributes to air pollution and can lead to respiratory issues and environmental harm.</p>");
out.println("                     </div>");
out.println("                  </div>");
out.println("                  <div class=\"col-md-6\">");
out.println("                     <div class=\"blog_box\">");
out.println("                        <div class=\"blog_img\"></div>");
out.println("                        <h4 class=\"prep_text\">Xylene...</h4>");
out.println("                        <p class=\"lorem_text\">");
out.println("");
out.println("Xylene, a common air pollutant originating from sources such as vehicle emissions and industrial activities, poses significant environmental and health risks. This volatile organic compound contributes to air pollution by participating in the formation of ground-level ozone and smog, which can lead to respiratory problems and worsen conditions like asthma. Prolonged exposure to xylene can have adverse health effects, including neurological and respiratory symptoms, as well as potential damage to the kidneys and liver. Additionally, xylene contamination in water sources can harm aquatic ecosystems. Consequently, efforts to reduce xylene pollution are crucial for safeguarding both the environment and human well-being.</p>");
out.println("                     </div>");
out.println("                  </div>");
out.println("               </div>");
out.println("            </div>");
out.println("         </div>");
out.println("      </div>");
out.println("<!-- about section end -->");
out.println("      <!-- client section start -->");
out.println("      <div class=\"client_section layout_padding\">");
out.println("         <div class=\"container\">");
out.println("            <div class=\"row\">");
out.println("               <div class=\"col-md-12\">");
out.println("                  <h1 class=\"about_taital\">Harm Full Effects</h1>");
out.println("                  <div class=\"bulit_icon\"><img src=\"images/bulit-icon.png\"></div>");
out.println("               </div>");
out.println("            </div>");
out.println("            <div class=\"client_section_2\">");
out.println("               <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images\\one.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Respiratory Issues</h3>");
out.println("                     <p class=\"client_text\">Xylene is a volatile organic compound that, when released into the air, can irritate the respiratory system, leading to symptoms like coughing, throat irritation, and exacerbation of respiratory conditions such as asthma. </p>");
out.println("                  </div>");
out.println("               </div>");
out.println("               <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images\\two.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Environmental Impact</h3>");
out.println("                     <p class=\"client_text\">Xylene pollution in water sources can harm aquatic ecosystems, affecting aquatic life and disrupting the balance of ecosystems. </p>");
out.println("                  </div>");
out.println("               </div>");
out.println("               <div class=\"client_taital_main\">");
out.println("                  <div class=\"client_left\">");
out.println("                     <div class=\"client_img\"><img src=\"images\\three.png\"></div>");
out.println("                  </div>");
out.println("                  <div class=\"client_right\">");
out.println("                     <h3 class=\"moark_text\">Air Pollution</h3>");
out.println("                     <p class=\"client_text\">Xylene contributes to the formation of ground-level ozone and smog, which can lead to poor air quality and exacerbate respiratory problems in affected areas. </p>");
out.println("                  </div>");
out.println("               </div>");
out.println("            </div>");
out.println("         </div>");
out.println("      </div>");
out.println("      ");
out.println("     ");
out.println("      <!-- footer section end -->");
out.println("      <!-- Javascript files-->");
out.println("      <script src=\"js/jquery.min.js\"></script>");
out.println("      <script src=\"js/popper.min.js\"></script>");
out.println("      <script src=\"js/bootstrap.bundle.min.js\"></script>");
out.println("      <script src=\"js/jquery-3.0.0.min.js\"></script>");
out.println("      <script src=\"js/plugin.js\"></script>");
out.println("      <!-- sidebar -->");
out.println("      <script src=\"js/jquery.mCustomScrollbar.concat.min.js\"></script>");
out.println("      <script src=\"js/custom.js\"></script>");
out.println("   </body>");
out.println("</html>");
%>